package com.fsoft.internet.models;

public class Payment extends PaymentKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.amount
     *
     * @mbg.generated Sun Mar 10 08:56:35 ICT 2024
     */
    private Integer amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.amount
     *
     * @return the value of payment.amount
     *
     * @mbg.generated Sun Mar 10 08:56:35 ICT 2024
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.amount
     *
     * @param amount the value for payment.amount
     *
     * @mbg.generated Sun Mar 10 08:56:35 ICT 2024
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
}