package com.fsoft.internet.models;

public class Record extends RecordKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.using_time
     *
     * @mbg.generated Sun Mar 10 08:56:35 ICT 2024
     */
    private Integer usingTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.using_time
     *
     * @return the value of record.using_time
     *
     * @mbg.generated Sun Mar 10 08:56:35 ICT 2024
     */
    public Integer getUsingTime() {
        return usingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.using_time
     *
     * @param usingTime the value for record.using_time
     *
     * @mbg.generated Sun Mar 10 08:56:35 ICT 2024
     */
    public void setUsingTime(Integer usingTime) {
        this.usingTime = usingTime;
    }
}